# File:
# ./fail2ban-data/filter.d/badbots.conf

[Definition]
badbots = Go-http-client|python-httpx|go-resty|Python-urllib
failregex = ^{"log":"[^ ]* <HOST> - .+ \[.*\] \\"(GET|POST|HEAD|PUT|DELETE|OPTIONS).*HTTP.*\\"(?:%(badbots)s)
ignoreregex =
