# File:
# ./fail2ban-data/filter.d/limit-req.conf

[Definition]
ngx_limit_req_zones = [^"]+
failregex = ^{"log":"\s*\[[a-z]+\] \d+#\d+: \*\d+ limiting requests, excess: [\d\.]+ by zone \\"(?:%(ngx_limit_req_zones)s)", client: <HOST>,
