# File:
# ./fail2ban-data/filter.d/no-scripts.conf

[Definition]
failregex = ^{"log":"[^ ]* <HOST> - .+ \[.*\] \\"(GET|POST|HEAD|PUT|DELETE|OPTIONS) /[^"]+\.(php|asp|cgi|exe|jsp|mvc|pl|scgi)( |\?)
ignoreregex =
