# File:
# ./fail2ban-data/filter.d/wrong-uri.conf

[Definition]
failregex = (?i)^{"log":"[^ ]* <HOST> - .+ \[.*\] \\"(GET|POST|HEAD|OPTIONS) /+(resolve|dns-query|xfs\.bxss\.me|db/|sql|phpmyadmin|pma|vk.com|xmlrpc|a2billing|apache|cfide|config|\.git|hnap|jenkins|jmx-|joomla|linuxsucks|muieblackcat|mysql|myadmin|n0w|owa-autodiscover|pbxip|recordings|script|shell|sqlite|vmskdl44rededd|vtigercrm|w00tw00t|webdav|websql|wordpress|xampp|xxbb)
           (?i)^{"log":"[^ ]* <HOST> - .*(/\.DS_Store|/bash|/windows|boot\.ini|/%%2e%%2e/%%2e%%2e/|\.\.%%252f\.\.%%252f|\.\./\.\./|\.\./\.\./\.\./|\.\.%%2f\.\.%%2f|etc/passwd|wp-includes|wp-content|wp-admin|wp-login|cgi-bin|burger-imperia|changelog|hundejo|hvd-store|jorgee|masscan|pizza-imperia|pizza-tycoon|servlet|testproxy|uploadify|backup|zabbix|webclient/|/\.env)
ignoreregex =